Reset subforms
navikt/smregistrering pull request #69
Opened 2020-08-24 12:17 UTC by johenie

2020-08-24 12:32 UTC, johenie commented
Har jeg glemt noen felter?

2020-08-25 08:21 UTC, sebdak requested changes
Som nevnt på slack -

Under MulighetForArbeid mangler hver RangePicker validering i onChange

2020-09-01 14:03 UTC, sebdak commented on client/src/components/Form/components/formSections/DiagnoseSection/DiagnoseSection.tsx
>                                  return updatedSchema;
```suggestion
                                validate('annenFraversArsak', updatedSchema);
                                validate('annenFraversArsakGrunn', updatedSchema);
                                validate('annenFraversArsakBeskrivelse', updatedSchema);
                                return updatedSchema;
```
Vi har en liten issue her, hvor man kan få feil på underspørsmål, som ikke går vekk før man prøver å submitte. Den foreslåtte endringen her er heller ikke så nice, da det vil komme feil på underspørsmål med én gang... Vi burde kanskje hatt en state i formen `attemptedSubmittet: boolean`. Hva tror du?

2020-09-01 14:04 UTC, sebdak commented on client/src/components/Form/components/formSections/DiagnoseSection/DiagnoseSection.tsx
>                                  return updatedSchema;
for å gjenskape feil:

1. klikk vekk alle valg under 3.3.1 Lovfestet fraværsgrunn
2. klikk vekk 3.1

2020-09-03 13:23 UTC, sebdak approved these changes

2020-09-03 13:23 UTC, sebdak commented on client/src/components/Form/components/formSections/MulighetForArbeidSection/MulighetForArbeidSection.tsx
> +                                            avventendeInnspillTilArbeidsgiver: value,
👀

2020-09-03 13:23 UTC, sebdak commented on client/src/utils/registrertSykmeldingUtils.ts
> +        schema.avventendeInnspillTilArbeidsgiver,
👀

2020-09-04 08:37 UTC, merged